### ISSUE TITLE
All Tags below 1.1.0 have a dependency on react 0.14. Why?

### ISSUE THREAD

**Issue by jhawthor** [react-d3/react-d3-tooltip#6]
All Tags below 1.1.0 have a dependency on react 0.14. Why?
When I try to install a version prior to 1.1.0 (0.7.0  OR 0.5.0) I get a dependency error for react 0.14.  

react-d3-core 0.4.2 does not have this issue.  When can this be fixed.  I cannot move to React 0.14 until Jan-Feb 2016. 

Also, is there a tag for 1.0.0?  The next largest tag below 1.1.0 (identified as the move to React 0.14) is 0.7.0?

**Comment by chilijung** [comment]
hi @jhawthor, I'm sorry I forget to remove react in dependencies. I've removed it in v1.1.1, if you are trying react version 0.13 , you can try to install react-d3-tooltip@0.2.0. after 0.2.0 I've update react to 0.14 version.

**Comment by jhawthor** [comment]
hi @chilijung, thanks for the update.
