### ISSUE TITLE
tooltip will not update when state update, it will remain the initial chart.

### ISSUE THREAD

**Issue by chilijung** [react-d3/react-d3-tooltip#8]

**Comment by maherbeg** [comment]
Yeah, this was a surprise and made it difficult to get this component working when dynamically retrieving the data needed to populate the graph.

**Comment by chilijung** [comment]
@maherbeg I'll try to fix this today! thanks for report the bug

**Comment by chilijung** [comment]
@maherbeg now support on npm @1.3.0 version!

**Comment by maherbeg** [comment]
Awesome thanks! Is there a pre-built version? (I'm building locally now, but it may be useful to others!)

**Comment by chilijung** [comment]
@maherbeg any suggestion to do that?

**Comment by maherbeg** [comment]
@chilijung What do you mean? I was mostly referring to the files in the root of the repository like https://github.com/react-d3/react-d3-tooltip/blob/master/react-d3-tooltip.js
